"""Bounded source-only compatibility of all original native adaptive candidates.

Recorded transaction prices are not quotes, fills, capacity or strategy economics.
This separate protocol never invokes an economic runner or an archive cache loader.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import time
import urllib.request
from collections import Counter
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Any

from kairos_backtest import aggtrades

from .compare import decode_intent, require_ready_adaptive_slot
from .inputs import UNIVERSE
from .intraday_references import EntryRequest, scan_daily_archive
from .runner import canonical, digest, load_plan, source_receipt, utc_now, write_json

SOURCE_PLAN_FILE_SHA256 = "89e1a6641e228365ffec5011da2f456f6af67d3a83d46ccfe037ff0f360f6748"
PUBLIC_ROOT = "https://data.binance.vision/data/futures/um/daily/aggTrades"
SLOT_FIELDS = {
    "symbol",
    "logical_decision_ms",
    "context_cut_ms",
    "input_window_sha256",
    "status",
    "reason",
    "regime",
    "intent",
    "source_clock_authority",
    "slot_id",
}


def sha(path: Path, deadline: float | None = None) -> str:
    fingerprint = hashlib.sha256()
    with path.open("rb") as stream:
        while block := stream.read(1024 * 1024):
            if deadline is not None and time.monotonic() >= deadline:
                raise TimeoutError("source-only hashing deadline")
            fingerprint.update(block)
    return fingerprint.hexdigest()


def verify_downloads(output: Path, downloads: list[dict[str, Any]], deadline: float) -> None:
    for receipt in downloads:
        # Only filenames generated by the fixed roster can be source witnesses.
        parts = receipt["filename"].split("-aggTrades-")
        if (
            len(parts) != 2
            or parts[0] not in UNIVERSE
            or Path(receipt["filename"]).name != receipt["filename"]
        ):
            raise ValueError("unexpected downloaded source identity")
        path = output / parts[0] / receipt["filename"]
        if path.stat().st_size != receipt["bytes"] or sha(path, deadline) != receipt["sha256"]:
            raise ValueError("downloaded official source bytes changed during the audit")


def load_source_plan(path: Path) -> dict[str, Any]:
    if path.stat().st_size > 32_768 or sha(path) != SOURCE_PLAN_FILE_SHA256:
        raise ValueError("unchanged separately sealed source-only protocol required")
    return json.loads(path.read_text(encoding="utf-8"))


def _ms(day: str) -> int:
    return int(datetime.fromisoformat(day).replace(tzinfo=UTC).timestamp() * 1000)


def original_requests(
    root: Path, plan: dict[str, Any], deadline: float
) -> tuple[list[EntryRequest], list[dict[str, Any]]]:
    """Check every byte-bound slot; do not regenerate or inspect original economics."""
    requests: list[EntryRequest] = []
    receipts = []
    for tape in plan["tapes"]:
        path = root / tape["window"] / "decisions.jsonl"
        if path.stat().st_size > 8 * 1024 * 1024 or sha(path) != tape["sha256"]:
            raise ValueError("original native tape bytes changed")
        start, end = _ms(tape["start"]), _ms(tape["end_exclusive"])
        expected = [(s, ts) for s in UNIVERSE for ts in range(start, end, 300_000)]
        counts: Counter[str] = Counter()
        file_digest = hashlib.sha256()
        candidates = position = 0
        with path.open("rb") as stream:
            for encoded in stream:
                if time.monotonic() > deadline:
                    raise TimeoutError("source-only native tape deadline")
                if len(encoded) > 16_384 or position >= len(expected):
                    raise ValueError("native tape slot bound changed")
                item = json.loads(encoded)
                symbol, ts = expected[position]
                if (
                    set(item) != SLOT_FIELDS
                    or canonical(item) + b"\n" != encoded
                    or item["symbol"] != symbol
                    or item["logical_decision_ms"] != ts - 1
                    or item["context_cut_ms"] != ts - 1
                    or not isinstance(item["input_window_sha256"], str)
                    or re.fullmatch(r"[0-9a-f]{64}", item["input_window_sha256"]) is None
                    or item["source_clock_authority"] != "HISTORICAL_EVENT_TIME_NOT_LIVE_RECEIPT"
                    or item["slot_id"]
                    != digest({k: item[k] for k in ("symbol", "logical_decision_ms", "input_window_sha256")})
                ):
                    raise ValueError("original native causal slot changed")
                require_ready_adaptive_slot(item)
                counts[item["status"]] += 1
                file_digest.update(encoded)
                if item["intent"] is not None:
                    intent = decode_intent(item["intent"])
                    if intent.symbol != symbol or intent.decision_ts_ms != ts - 1:
                        raise ValueError("native intent escaped its original causal slot")
                    requests.append(
                        EntryRequest(
                            symbol=symbol,
                            intent_id=intent.intent_id,
                            decision_ts_ms=intent.decision_ts_ms,
                            entry_eligible_ts_ms=intent.entry_eligible_ts_ms,
                            expires_ts_ms=intent.entry_expires_ts_ms,
                            completion_ts_ms=intent.decision_ts_ms + 100,
                            transport_delay_ms=0,
                        )
                    )
                    candidates += 1
                position += 1
        if (
            position != tape["slots"]
            or position != len(expected)
            or candidates != tape["candidates"]
            or file_digest.hexdigest() != tape["sha256"]
            or sha(path) != tape["sha256"]
        ):
            raise ValueError("complete original native tape roster changed during inspection")
        receipts.append({**tape, "statuses": dict(sorted(counts.items()))})
    if [request.intent_id for request in requests] != plan["candidate_ids"]:
        raise ValueError("all original candidates in original order required, no selection")
    requested_days = {
        (r.symbol, datetime.fromtimestamp(r.entry_eligible_ts_ms / 1000, UTC).date().isoformat())
        for r in requests
    }
    if requested_days != {(a["symbol"], a["day"]) for a in plan["archives"]}:
        raise ValueError("archive roster differs from complete candidate roster")
    return requests, receipts


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req: Any, fp: Any, code: Any, msg: Any, headers: Any, newurl: Any) -> None:
        return None


def fetch_public_file(url: str, target: Path, maximum: int, deadline: float) -> dict[str, Any]:
    """One fixed public GET, bounded and create-only; retain failed partial evidence."""
    if not url.startswith(PUBLIC_ROOT + "/") or any(s in url for s in ("?", "#", "..", "\\")):
        raise ValueError("fixed public archive URL required")
    if type(maximum) is not int or maximum <= 0:
        raise ValueError("positive download bound required")
    if target.exists():
        raise FileExistsError("download output already exists, no in-place retry")
    remaining = deadline - time.monotonic()
    if remaining <= 0:
        raise TimeoutError("public source deadline before GET")
    opener = urllib.request.build_opener(_NoRedirect())
    request = urllib.request.Request(url, headers={"User-Agent": "KairosSourceAudit/1.0"})
    started = utc_now()
    with opener.open(request, timeout=min(20, remaining)) as response:
        if response.status != 200 or response.geturl() != url:
            raise ValueError("public source did not return the exact fixed URL")
        declared = response.headers.get("Content-Length")
        if declared is not None and (not declared.isdecimal() or int(declared) > maximum):
            raise ValueError("public source exceeds its declared bounded bytes")
        count = 0
        fingerprint = hashlib.sha256()
        with target.open("xb") as stream:
            while True:
                if time.monotonic() > deadline:
                    raise TimeoutError("public source streaming deadline")
                block = response.read(min(65_536, maximum - count + 1))
                if not block:
                    break
                count += len(block)
                if count > maximum:
                    raise ValueError("public source exceeds streaming byte bound")
                stream.write(block)
                fingerprint.update(block)
        if declared is not None and count != int(declared):
            raise ValueError("public source body length differs from header")
    return {
        "url": url,
        "filename": target.name,
        "bytes": count,
        "sha256": fingerprint.hexdigest(),
        "started_utc": started,
        "completed_utc": utc_now(),
        "http_status": 200,
        "requests": 1,
        "redirects": 0,
    }


def run(plan_path: Path, native_root: Path, output: Path) -> int:
    plan_path = plan_path.resolve(strict=True)
    native_root = native_root.resolve(strict=True)
    output = output.resolve()
    plan = load_source_plan(plan_path)
    for protected in (native_root, plan_path.parent):
        if output == protected or output.is_relative_to(protected) or protected.is_relative_to(output):
            raise ValueError("new output must be disjoint from native evidence and source")
    if output.exists() or not output.parent.is_dir():
        raise ValueError("fresh task output under an existing parent required, never retry in place")
    if output.parent != plan_path.parents[3] / "runtime":
        raise ValueError("source audit output must be a direct child of the workspace runtime directory")
    if shutil.disk_usage(output.parent).free < 1024 * 1024 * 1024:
        raise ValueError("one GiB free disk reserve required before bounded public source fetch")
    base_path = plan_path.parent / "plan.json"
    base = load_plan(base_path)
    base_file_sha256 = sha(base_path)
    sources = source_receipt(base, base_path)
    if digest(base) != plan["original_plan_sha256"]:
        raise ValueError("original native protocol changed")
    sources["aggregate_parser_sha256"] = sha(Path(aggtrades.__file__))
    sources["source_plan_file_sha256"] = sha(plan_path)
    started = time.monotonic()
    deadline = started + plan["limits"]["max_wall_seconds"]
    requests, tapes = original_requests(native_root, plan, deadline)
    output.mkdir(exist_ok=False)
    write_json(output / "sealed-source-plan.json", plan)
    write_json(
        output / "before.json",
        {
            "state": "RUNNING",
            "started_utc": utc_now(),
            "sources": sources,
            "tapes": tapes,
            "original_plan_or_tapes_changed": False,
            "economic_evidence_read": False,
        },
    )
    downloads: list[dict[str, Any]] = []
    archives = []
    bytes_read = rows = 0
    phase = "FETCH"
    current_archive = None
    try:
        for archive in plan["archives"]:
            current_archive = archive
            phase = "FETCH"
            symbol, day = archive["symbol"], date.fromisoformat(archive["day"])
            filename = f"{symbol}-aggTrades-{day}.zip"
            directory = output / symbol
            directory.mkdir(exist_ok=True)
            archive_path = directory / filename
            checksum_path = directory / (filename + ".CHECKSUM")
            url = f"{PUBLIC_ROOT}/{symbol}/{filename}"
            print(f"phase=public_source_fetch symbol={symbol} day={day}", flush=True)
            checksum = fetch_public_file(url + ".CHECKSUM", checksum_path, 512, deadline)
            available = min(
                plan["limits"]["max_compressed_bytes_each"],
                plan["limits"]["max_compressed_bytes_total"] - bytes_read,
            )
            downloaded = fetch_public_file(url, archive_path, available, deadline)
            bytes_read += downloaded["bytes"]
            downloads.extend((checksum, downloaded))
            write_json(output / f"downloads-{len(archives) + 1:02d}.json", downloads[-2:])
            selected = [
                r
                for r in requests
                if r.symbol == symbol
                and datetime.fromtimestamp(r.entry_eligible_ts_ms / 1000, UTC).date() == day
            ]
            print(f"phase=whole_archive_integrity symbol={symbol} day={day}", flush=True)
            phase = "WHOLE_ARCHIVE_INTEGRITY"
            receipt = scan_daily_archive(
                archive_path,
                checksum_path,
                symbol,
                day,
                selected,
                deadline=deadline,
                max_compressed_bytes=plan["limits"]["max_compressed_bytes_each"],
                max_uncompressed_bytes=plan["limits"]["max_uncompressed_bytes_each"],
                max_rows=min(plan["limits"]["max_rows_each"], plan["limits"]["max_rows_total"] - rows),
            )
            if (
                receipt["archive_sha256"] != downloaded["sha256"]
                or receipt["archive_bytes"] != downloaded["bytes"]
                or receipt["checksum_sidecar_sha256"] != checksum["sha256"]
            ):
                raise ValueError("scanner source differs from the official GET byte witnesses")
            rows += receipt["rows"]
            archives.append(receipt)
            write_json(output / f"archive-{len(archives):02d}.json", receipt)
            print(f"phase=source_checked archives={len(archives)} rows={rows}", flush=True)
        phase = "FINAL_SOURCE_BINDING"
        verify_downloads(output, downloads, deadline)
        after_requests, after_tapes = original_requests(native_root, plan, deadline)
        after_base = load_plan(base_path)
        after_sources = source_receipt(after_base, base_path)
        if (
            after_requests != requests
            or after_tapes != tapes
            or after_sources
            != {
                k: v
                for k, v in sources.items()
                if k not in {"aggregate_parser_sha256", "source_plan_file_sha256"}
            }
            or sha(Path(aggtrades.__file__)) != sources["aggregate_parser_sha256"]
            or sha(plan_path) != sources["source_plan_file_sha256"]
            or sha(base_path) != base_file_sha256
            or digest(after_base) != digest(base)
        ):
            raise ValueError("source or native evidence changed during source-only audit")
        records = [record for archive in archives for record in archive["requests"]]
        by_id = {record["intent_id"]: record for record in records}
        if len(by_id) != len(requests) or set(by_id) != set(plan["candidate_ids"]):
            raise ValueError("every original candidate must have exactly one source-only outcome")
        records = [by_id[identifier] for identifier in plan["candidate_ids"]]
        result = {
            "schema": "kairos.adaptive.intraday-source-result.v1",
            "state": "COMPLETED",
            "purpose": plan["purpose"],
            "sources": sources,
            "native_tapes": tapes,
            "archives": archives,
            "downloads": downloads,
            "references": records,
            "reference_statuses": dict(sorted(Counter(r["status"] for r in records).items())),
            "scheduled_native_slots": sum(t["slots"] for t in tapes),
            "original_candidates": len(requests),
            "archive_rows_checked": rows,
            "compressed_bytes_fetched": bytes_read,
            "clock_policy": plan["clock_policy"],
            "source_fidelity": plan["source_fidelity"],
            "wall_seconds": round(time.monotonic() - started, 3),
            "completed_utc": utc_now(),
            "economics_computed": False,
            "quote_observed": False,
            "fill_qualified": False,
            "capacity_qualified": False,
            "strategy_winner": None,
            "selection_credit": False,
            "native_context_freshly_requalified": False,
            "readiness": plan["readiness"],
            "source_before_after_equal": True,
            "downloaded_sources_finally_equal": True,
            "original_plan_file_sha256": base_file_sha256,
        }
        write_json(output / "result.json", result)
        print(f"state=COMPLETED candidates={len(requests)} rows={rows}", flush=True)
        return 0
    except Exception as exc:
        write_json(
            output / "failure.json",
            {
                "state": "FAILED_CLOSED",
                "error_type": type(exc).__name__,
                "phase": phase,
                "archive": current_archive,
                "source_error": str(exc)[:512],
                "archives_completed": len(archives),
                "rows_checked": rows,
                "compressed_bytes_fetched": bytes_read,
                "completed_utc": utc_now(),
                "source_prerequisite_resolved": False,
                "economics_computed": False,
                "readiness": plan["readiness"],
                "no_automatic_retry": True,
            },
        )
        print(f"state=FAILED_CLOSED error_type={type(exc).__name__}", flush=True)
        return 1


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan", required=True, type=Path)
    parser.add_argument("--native-root", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    raise SystemExit(run(args.plan, args.native_root, args.output))


if __name__ == "__main__":
    main()
